### ISSUE TITLE
The destination folder was wiped 

### ISSUE THREAD

**Issue by MdShaadmanLodhi** [AdmiralSYN-ACKbar/bulkcheck#2]
Hi OP I have used this software few hours ago 
I had run the exe file 
entered the key 
Selected the .csv
and the export location 
run the ENGAGE Button and 
bhamm my destination folder's content was wiped 
gone !!!!!!
@AdmiralSYN-ACKbar  please check this I have lost some imp files ...

**Comment by AdmiralSYN-ACKbar** [comment]
Sorry that happened. The export box was intended to be have a file name, not a folder path, and overwrite if it already exists. I never tested to see what would happen if a folder, rather than a file, were specified. I'm changing the code now to have a user re-enter a path if it already exists to avoid future instances of this.

Unfortunately, in my testing of a couple of common file recovery tools, I was unable to recover items deleted by Powershell's Remove-Item command. Please let me know if you're able to get that working.

**Comment by MdShaadmanLodhi** [comment]
yeah, do the necessary changes 
and the worst part was I was unable to recover the files :(
my recovery software usually works in every situation but I had no luck this the main thing, It did not work there were some error on the command prompt.
Hope the bugs will be fixed..

**Comment by AdmiralSYN-ACKbar** [comment]
Export path validation has now been added. The Export Path field will no longer accept folder paths, forcing a user to enter a file-path instead. Additionally, the program will force the user to re-enter a file path if it already exists rather than overwriting an existing file.

![exportvalidation](https://user-images.githubusercontent.com/55727245/121788203-43485b80-cb80-11eb-8ddf-fee7010e251c.PNG)

Admiralty Labs apologizes for the loss of your files and thanks you for bringing attention to this issue. Although we cannot assist you in recovering your files, please email sorry@admiralsyn-ackbar.com to receive a token of compensation.
