### ISSUE TITLE
Application contains trojan

### ISSUE THREAD

**Issue by leifdavisson** [AdmiralSYN-ACKbar/bulkcheck#6]
https://www.virustotal.com/gui/file/0af27f1e642a19cdbea573ae0564ef01ee8a93efb6b042ea683dbe5772d4292f/detection

**Comment by AdmiralSYN-ACKbar** [comment]
This is very alarming, but I do not know what exactly you are posting a report on, as it does not appear to be the current PS1 file in the repo. To confirm, I downloaded the latest file from the repo and uploaded it to Virus Total and got no detections:
https://www.virustotal.com/gui/file/ab01f820c889dd53cb42fd9dcafa1797230a98409dd617b36b727e807f71b7ae

What did you upload that produced these results? If it was the old EXE, this produced false positives due to the compilation tool I used to convert the PS1 to an EXE, which is why I removed it from the repo. Can you provide more information?
