### ISSUE TITLE
Infected with Trojan.GenericKD.47061246 (?)

### ISSUE THREAD

**Issue by topfuel75** [AdmiralSYN-ACKbar/bulkcheck#7]
If I try to download 'AbuseIPDB_Bulk_Checker.exe' Bitdefender automatically delete the file with the following message:
Feature: Antivirus
The file H:\Downloads\AbuseIPDB_Bulk_Checker.JjtXBI7O.exe.part is infected with Trojan.GenericKD.47061246 and was moved to quarantine.

If I download 'Source code (zip)' and test it at VirusTotal a lot of vendors flag it as malicious. 
The report is at 
https://www.virustotal.com/gui/file/840a800c675b7827929cd82db013d7596bba67acb29aec99ca1804db6ad38df5

Both of the downloads was made from  https://github.com/AdmiralSYN-ACKbar/bulkcheck/releases/tag/1.0

**Comment by AdmiralSYN-ACKbar** [comment]
Hi Topfuel,

The EXE version is flagged as a "generic" Trojan because many antivirus engines flag all EXEs generated from PowerShell scripts using Powershell Pro Tools as malicious (regardless of if they actually are or not). You can read much more about the issue at (https://docs.poshtools.com/powershell-pro-tools-documentation/packaging/anti-virus).

I have removed the EXE from the link that you mentioned to avoid further confusion regarding this issue, as it has arisen before. The PS1 is now the only file being hosted - feel free to test that through VirusTotal to verify that it is malware-free. The next release should update the source code file that is hosted under the "Releases" page. Please let me know if you have any further questions on this.

**Comment by topfuel75** [comment]
Thanks for the information.

Just to clarify, my post wasn't meant to be any critic. It was rather an observation and an informal notice.
I wasn't aware that a false positive trojan you linked to. It must be quite frustrating.

**Comment by AdmiralSYN-ACKbar** [comment]
Thanks topfuel, no worries! I'm glad you pointed this out, hopefully it will be resolved going forward.
